config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets
  resources :users
  root 'tweets#top'
  get 'tags/:id' => 'tags#show', as: 'tag'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweets

end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :tag
	belongs_to :user
	validates :text, length: { in: 1..300}
	attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :tweets

	validates :user_name, length: { in: 1..20 },presence: true
	validates :introduction, length: { maximum:  100}

	attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_tweet
  	before_action :configure_permitted_parameters, if: :devise_controller?

 	def after_sign_in_path_for(resource)
 		user_path(current_user.id)
	end

 
protected
	def configure_permitted_parameters
  # 新規登録に使用するカラム
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :email, :password])
    end

private

	def set_tweet
		@tweet = Tweet.new
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
  	@user = current_user
    @tweet_new = Tweet.new
    @tags = Tag.all

    @tag = Tag.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def top
  end
  def index
    @tweets = Tweet.all
    @tags = Tag.all
  end



  def show
    @tweet_show = Tweet.find(params[:id])
    @user = User.find(current_user.id)
    @tags = Tag.all
  end



  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    tweet.save
    redirect_to user_path(current_user.id)
  end

  def edit
  end

  def update
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to user_path(current_user.id)
  end
  private
  def tweet_params
    params.require(:tweet).permit(:text, :tag_id, :free_word, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	if User.find_by(id: params[:id])

  		@user = User.find(params[:id])
  		@tweet_new = Tweet.new
  		@tweets_show = @user.tweets
      @tags = Tag.all

  	else redirect_to user_path(current_user.id)
  	end
  end

  def edit
  	@user = User.find(params[:id])
  		if @user != current_user
  			redirect_to user_path(current_user.id)
  		end
  end

  def update
  	@user = User.find(params[:id])
  		if @user.update(user_params)
  			redirect_to user_path(current_user.id)
  		else
  			render :edit
  		end
  end

  private
  def user_params
  	params.require(:user).permit(:user_name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>pochipochi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<!--   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!--   <script type="text/javascript">
    $(function() {
      alert();
    })
  </script> -->
  </head>

  <body>
    <!-- ヘッダー部分 -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-brand">pochipochi</p>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <!-- サインインしてるかどうか -->
      <% if user_signed_in? %>
      <li class="">
        <%= link_to " "+current_user.user_name,user_path(current_user.id), class: "glyphicon glyphicon-home" %>
      </li>
      <li class="">
        <a id="modal-open" class="glyphicon glyphicon-pencil button-link"> 投稿</a>
      </li>
      <li class="">
        <%= link_to ' ログアウト',destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete %>
      </li>
      <% else %>
      <li class="">
        <%= link_to" ホーム",root_path, class: "glyphicon glyphicon-home" %>
      </li>
      <li class="">
      </li>
      <li class="">
        <%= link_to" サインアップ",new_user_registration_path, class: "glyphicon glyphicon-user" %>
      </li>
      <li class="">
        <%= link_to" ログイン",new_user_session_path, class: "glyphicon glyphicon-log-in" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
    <%= yield %>
      <div id="modal-overlay">
        <div class="col-lg-3">
        </div>
          <div class="col-lg-6">
            <div id="modal-content">
              <h3>新規投稿</h3>
              <%= form_for(@tweet) do |f| %>

                <h3>内容</h3>
                <%= f.text_area :text %>
                <h3>投稿タグ</h3>
                <%= f.collection_select :tag_id, Tag.all, :id, :tag_name %>
                <h3>フリーワード</h3>
                <%= f.text_field :free_word %>
                <h3>画像</h3>
                <%= f.attachment_field :image %>
                <%= f.submit '投稿' %>

              <% end %>

              <p><a id="modal-close" class="button-link">閉じる</a></p>
            </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tags/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'tweets/side', tweet: @tweet, user: @user, tags: @tags %>
		</div>
		<div class="col-lg-7">
		<h2><%= @tag.tag_name %></h2>
			<% @tag.tweets.reverse_each do |data| %>
				<div class="panel panel-default">
					<div class="panel-heading">
						<!-- パネルのヘッダー部分 -->
						<%= attachment_image_tag data.user, :image, :fill, 30, 30, format:'jpeg', fallback: "noimage.png",size: '50x50', class: "icon" %>
						<%= link_to data.user.user_name,  user_path(data.user.id)  %>
					</div>
					<div class="panel-body">
						<!-- パネルの内容の部分 -->
						<%= data.text %>
					</div>
					<div class="panel-footer">
						<!-- パネルのフッターの部分 -->
						<%= attachment_image_tag data, :image, :fill, 500,300, format:'jpeg', class: "picbox" %><br>
						<p class="font20 postbox">フリーワード:<%= data.free_word %></p>
						<% if data.user == current_user %>
								<%= link_to "削除", tweet_path(data), method: :delete,data: { confirm: '削除しますか？' }, class: "btn btn-danger postbox" %>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/tweets/_side.html.erb


		<h2 class="icon_div">ユーザー情報</h2>
			<div class="icon_div">
				<%= attachment_image_tag(user, :image, :fill, 100, 100, format:'jpeg', fallback: "noimage.png",size: '100x100', class: "icon") %>
			</div>
		<table class="table">
			<thead>
				<tr>
					<th class="side_font"><%= user.user_name %></th>
				</tr>
				<tr>
					<th><%= user.introduction %></th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<% if user.id == current_user.id %>
					<td><%= link_to "プロフィール編集", edit_user_path(current_user), class: "btn btn-success side_font" %></td>
					<% end %>
				</tr>
			</tbody>
		</table>
		<div class="tag_link_box">
			<h3>タグ一覧</h3>
			<% tags.each do |tag| %>
			<div class="font20">
				<%= link_to tag.tag_name, tag_path(tag.id) %>
			</div>
			<% end %>
		</div>

app/views/tweets/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'tweets/side', user: current_user, tags: @tags %>
		</div>
		<div class="col-lg-7">
			<h2>Tweet</h2>
			<table class="table table-hover">
				<thead>
					<tr>
						<th>icon</th>
						<th>text</th>
					</tr>
				</thead>
				<tbody>
					<% @tweets.each do |data| %>
						<tr>
							<!-- プロフィールアイコン -->
							<td><%= attachment_image_tag(data.user, :image, :fill, 30, 30, format:'jpeg', fallback: "noimage.png",size: '30x30', class: "icon") %></td>
							<td><%= link_to data.text, tweet_path(data.id) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/tweets/new.html.erb
<div id="modal-content">
	<h1>新規投稿</h1>
	<%= form_for(@tweet) do |f| %>

		<h3>内容</h3>
		<%= f.text_area :text %>
		<h3>投稿タグ</h3>
		<%#= f.select tag_id, [["FFXIV", "FFXIV"], ["DQX", "DQX"]] %>
		<h3>free word</h3>
		<%#= f.text %>
		<%= f.submit '投稿' %>

	<% end %>
	<p><a id="modal-close" class="button-link">閉じる</a></p>
</div>

app/views/tweets/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'tweets/side', user: @tweet_show.user, tags: @tags %>
		</div>
		<div class="col-lg-9">
			<h2><%= @tweet_show.user.user_name %>の投稿詳細</h2>
			<div class="panel panel-default">
				<div class="panel-body">
					<!-- パネルの内容の部分 -->
					<%= @tweet_show.text %><br>
				</div>
				<div class="panel-footer">
					<!-- パネルのフッターの部分 -->
					<%= attachment_image_tag @tweet_show, :image, :fill, 800,600, format: 'jpeg' %><br>
					<p class="font20 postbox">タグ:<%= @tweet_show.tag.tag_name %></p>
					<p class="font20 postbox">フリーワード:<%= @tweet_show.free_word %></p>
					<% if @tweet_show.user == current_user %>
					<%= link_to "削除", tweet_path(@tweet_show), method: :delete,data: { confirm: '削除しますか？' }, class: "btn btn-danger postbox" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/tweets/top.html.erb
<p>ここは様々なゲームのことを気軽に話せる場所です!<br>
思ったことや、気づいたこと、また記念写真等それぞれのスタイルに合わせて投稿してください！<p>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<div class="devise_window">
	<h1>ユーザー情報</h1>
	<%= form_for(@user) do |f| %>
	<h4>ユーザーアイコン</h4>
	<%= f.attachment_field :image %>
	<h4>ユーザーネーム</h4>
	<%= f.text_field :user_name , class: "form-group form-control"%>
	<h4>自己紹介</h4>
	<%= f.text_area :introduction, class: "form-group form-control" %>

	<%= f.submit "ユーザー情報の更新", class: "btn btn-default" %>

	<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'tweets/side', tweet: @tweet, user: @user, tags: @tags %>
		</div>
		<div class="col-lg-7">
			<h2><%= @user.user_name %>さんの投稿一覧</h2>
			<% @tweets_show.reverse_each do |data| %>
				<div class="panel panel-default">
					<div class="panel-heading">
					<!-- パネルのヘッダー部分 -->
						<%= attachment_image_tag data.user, :image, :fill, 30, 30, format:'jpeg', fallback: "noimage.png",size: '50x50', class: "icon" %>
						<%= data.user.user_name %>
					</div>
					<div class="panel-body">
						<!-- パネルの内容の部分 -->
						<%= data.text %><br>
					</div>
					<div class="panel-footer">
						<!-- パネルのフッターの部分 -->
						<%= attachment_image_tag data, :image, :fill, 500,300, format:'jpeg', class: "picbox" %><br>
						<p class="font20 postbox">タグ:<%= data.tag.tag_name %></p>
						<p class="font20 postbox">フリーワード:<%= data.free_word %></p>
						<% if data.user == current_user %>
							<%= link_to "削除", tweet_path(data), method: :delete,data: { confirm: '削除しますか？' }, class: "btn btn-danger postbox" %>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>